### PR TITLE
Replace stems/join-monster with join-monster/join-monster

### PR DESCRIPTION
**Pull request by mtsmfm**
I think stems/join-monster is the old repo though, please tell me if I'm wrong.

---

I'm confused a bit because https://join-monster.readthedocs.io/en/latest/ indicates https://github.com/stems/join-monster

### CODE REVIEW

**Comment by lorensr** [comment]
You are correct, thanks!

**Comment by mtsmfm** [comment]
@lorensr I'm not sure how the page is built though, it seems it hasn't got updated yet 🤔 

https://join-monster.readthedocs.io/en/latest/

**Comment by lorensr** [comment]
@mtsmfm correct—we lost access to the email address on the readthedocs account, so we're going through the recovery process, ETA 6 weeks 😆 Sorry for the trouble!

**Comment by lorensr** [comment]
Recovered, and docs updated!

**Pull request merged**
