### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by amosyuen**
- Fix up package.json script commands to be cross platform compatible
- Fix up tests so that the computer doesn't need all the different SQL versions installed locally. Can test using docker and leave the local computer clean.

### CODE REVIEW

**Comment by GlennMatthys** [comment]
Nice work. I will try to review this asap.

**Comment by amosyuen** [comment]
@GlennMatthys Have you had a chance to review this yet? Been a couple of months...

**Comment by amosyuen** [comment]
@GlennMatthys Poke

**Comment by lorensr** [comment]
Sorry for the radio silence! We're forming a new team to maintain this repo and respond to PRs, if you're interested: #399

**Comment by lorensr** [comment]
@amosyuen This looks great! I'm getting this error:

```
join-monster git:(upstream ⚡ amosyuen-test) 1A $ npm run db-setup

> join-monster@2.1.1 db-setup /Users/me/gh/join-monster
> bash bin/setup-docker-db

 setting up mysql server...
 MYSQL_URL=mysql://root@localhost:13306/
 creating database test1
 creating database test2
 mysql server setup

 setting up postgres server...
 PG_URL=pg://root@localhost:15432/
 creating database test1
Error response from daemon: No such container: joinmonster-test-postgres
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! join-monster@2.1.1 db-setup: `bash bin/setup-docker-db`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the join-monster@2.1.1 db-setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2020-04-10T06_56_08_130Z-debug.log
```

**Comment by lorensr** [comment]
This was added in #409

**Pull request closed without merging**
