### PR TITLE
Add the ability for scalars to be powered by sqlTables

### PR DESCRIPTION
**Pull request by airhorns**
join-monster excels at retrieving exactly the fields asked for by a given GraphQL query, but sometimes, there isn't an exact 1-1 correspondence between the desired fields in a GraphQL API and the table structure powering the system. Sometimes, data is normalized in the database or broken out into many tables for performance or reporting reasons or whatever, and join-monster supports these non 1-1 mappings fine with sqlExpr, alwaysFetch, and custom resolvers just fine, except when the "virtual" field is a scalar.

I've ended up having to use a few custom scalars in my application, mostly from the `graphql-scalars` package as well as a couple other random ones, and I have one that is powered by a whole other table in the actual database schema. As an example, I have a `Post` object with normal fields that map to columns, but then a `tags` field on the Post that should return a string of tags, where the Tag is a custom scalar to apply some special parsing and formatting to the tag. The tags are stored in their own tags table in the database. To expose this using `join-monster`, I could create a whole new `GraphQLObjectType` to represent Tags and then have a `{name, id}` field or whatever, but I feel like that is changing the design of the API to accomodate join-monster (and GraphQL to an extent), instead of making the nicest API for developers, which would just be a plain old array of strings.

So, I'd like to be able to do a `GraphQLList` of `Tag`, where `Tag` is a `new GraphQLScalar`, and have `join-monster` traverse that join and fetch my tags from the database. Turns out the only thing preventing this was the whitelist of types that `join-monster` looks for `sqlTable` on, so that's the only actual functional change in this PR.

This is probably a pretty rare thing, but it's super handy for these custom scalars, as well as the JSON scalar escape hatch that folks might use to escape the strict typing shackles of GraphQL when they need to.

### CODE REVIEW

**Comment by airhorns** [comment]
ping @lorensr <3

**Comment by lorensr** [comment]
This is a great feature, thanks! Can you include your tests in `npm test`? Either by adding the file to one of the test scripts, or adding a new script and running it from `bin/test`.

Like `"testsqlite3": "NODE_ENV=test ava test/*.js test/pagination/scalars.js",`

Also, they're failing for me:

```
$ NODE_ENV=test npx ava test/pagination/scalars.js

  ✖ it should get a scalar via a join or batch and resolve it 
    ℹ This type of pagination not supported on this dialect

  ✔ it should get a scalar list and resolve it
  ✖ it should get a connection of scalars and resolve it 
    ℹ Cannot read property 'map' of undefined


  2 tests failed

  it should get a scalar via a join or batch and resolve it
    ℹ This type of pagination not supported on this dialect


  test/pagination/scalars.js:54

   53:                                         
   54:   errCheck(t, errors)                   
   55:   t.deepEqual('foo', data.post.firstTag)

  Difference:

  - [
  -   GraphQLError {
  -     locations: [
  -       Object { … },
  -     ],
  -     message: 'This type of pagination not supported on this dialect',
  -     path: [
  -       'post',
  -     ],
  -   },
  - ]
  + undefined

  › errCheck (test/_util.js:25:5)
  › test/pagination/scalars.js:54:3



  it should get a connection of scalars and resolve it
    ℹ Cannot read property 'map' of undefined


  test/pagination/scalars.js:37

   36:                      
   37:   errCheck(t, errors)
   38:   t.deepEqual(       

  Difference:

  - [
  -   GraphQLError {
  -     locations: [
  -       Object { … },
  -     ],
  -     message: 'Cannot read property \'map\' of undefined',
  -     path: [
  -       'post',
  -       'tagsConnection',
  -     ],
  -   },
  - ]
  + undefined

  › errCheck (test/_util.js:25:5)
  › test/pagination/scalars.js:37:3
  ```

**Comment by alexbbt** [comment]
The code looks good, but as @lorensr said, the tests are failing

**Comment by airhorns** [comment]
Ok, rebased, fixed this to actually get run by the tests, and fixed the tests!

**Comment by airhorns** [comment]
ping @lorensr 💖

**Comment by lorensr** [comment]
Thanks a lot! Sorry for the wait 😆

**Comment by lorensr** [comment]
Published in `3.1.0` https://github.com/join-monster/join-monster/blob/master/docs/CHANGELOG.md#v310-january-17-2022-

**Pull request merged**
