### PR TITLE
feat: 1-to-1 join

### PR DESCRIPTION
**Pull request by wesselvdv**
This is a proposed solution for joining on tables where only one column is of interest. Utilising the LATERAL join type in Postgres makes this quite easy.

I added two new properties for a field (sqlForeignColumn & sqlForeignTable). Same as with sqlColumn, sqlForeignColumn is not required if the name of the field is the same as the intended foreign column name. The sqlForeignTable is expected to be a function that returns a string, much like sqlJoin. For using a LATERAL join you'll either need to return a subquery or a function that does roughly the same.

I am using this with Postgres so I put an assert on it for that dialect to prevent errors on other dialects.

Could solve #311, #198, #227 and #57

### CODE REVIEW

**Comment by wesselvdv** [comment]
Interesting thing is that I thought this approach would allow me to achieve a good performance increase, but the contrary is happening. It seems to be slower than the computed column approach in Postgres that I am utilising now.

I also thought about that way I implemented this, and a better approach might be to scrap the specific properties I added (sqlForeign*) and just look for a combination of a sqlColumn and sqlJoin.

**Comment by GlennMatthys** [comment]
What's the specific problem you're trying to solve? Why a LATERAL of an INNER join?

**Comment by GlennMatthys** [comment]
In the meanwhile, I'd like to discuss this API extension further on this wiki page: https://github.com/acarl005/join-monster/wiki/Proposal:-1-on-1-join

**Comment by alexbbt** [comment]
If this is still something you are interested in, please update your PR and discuss the proposal with us further.

**Comment by nicoabie** [comment]
I'm closing this one because of lack of activity, feel free to reopen if still interested in working on this!

**Pull request closed without merging**
