### PR TITLE
feat: allow manual offset

### PR DESCRIPTION
**Pull request by adampash**
Addresses https://github.com/stems/join-monster/issues/280. I haven't added any tests, but there aren't currently any regressions, which seems like a good sign. Let me know if you're amenable to this, and if so, what I might need to add to get this merged.

Thanks!

### CODE REVIEW

**Comment by pradel** [comment]
Any chance to see this merged soon? Thanks for the great work!

**Comment by GlennMatthys** [comment]
No merging without tests, sorry. I am open to this offset/limit idea though. API wise it looks good too.

**Comment by alexbbt** [comment]
If you update this with tests, we can work to get it in our 3.0 release

**Comment by nicoabie** [comment]
I'm closing this one because of inactivity, feel free to reopen if you still want to work on it!

**Comment by nicoabie** [comment]
Reopening because PR looks good and has an attached issue, we just need someone to come up with tests.

**Comment by nicoabie** [comment]
Will continue work in #535

**Pull request closed without merging**
