### PR TITLE
Fixes assert in AST node to include unions and interfaces.

### PR DESCRIPTION
**Pull request by ctoledoperez**
Unions and Interfaces where not being processed directly from a query. #229 #301 
There was an assert  checking for 'table' type when 'union' type (unions and interfaces) can be queried too

### CODE REVIEW

**Comment by acarl005** [comment]
Awesome! Thanks for fixing. Can you remove the `.sl3` files before I merge?

**Comment by pchinea** [comment]
Fixed! In any case, should not these product files be excluded from git?

**Comment by idibidiart** [comment]
Any update on the merge?

**Comment by aaronwhite** [comment]
Hey friendly neighborhood Join Monster maintainers, this would be very helpful if merged!

**Comment by theogravity** [comment]
Pinging @acarl005

**Pull request merged**
