### PR TITLE
allow limit on sqlite and mysql

### LINKED ISSUE #243: Allow limit without pagination on `sqlite3` or `mysql`
I would like to use `join-monster` with `sqlite3` or `mysql` database, but it prevents me setting the `limit`.

You state in the docs, that limit can only be used if pagination is supported for your SQL dialect. But I do not see why not allowing the use of limit with `sqlite3` or `mysql` if you want to use it without pagination?

### PR DESCRIPTION
**Pull request by mitjade**
Allow setting a limit for sqlite3 and mysql dialects.

Fixes #243

### CODE REVIEW

**Comment by mitjade** [comment]
Tests should pass, I made a previous PR with exactly the same code that passed. Just wanted to make a fresh one with out all necessary commits.

**Comment by lorensr** [comment]
Sorry for the radio silence! We're forming a new team to maintain this repo and respond to PRs, if you're interested: #399

**Comment by alexbbt** [comment]
If you update this with tests, we can work to get it in our 3.0 release

**Comment by nicoabie** [comment]
I'm closing this one because of inactivity, feel free to reopen if you still want to work on it!

**Comment by nicoabie** [comment]
Reopening because PR looks good and has an attached issue, we just need someone to come up with tests.

**Comment by nicoabie** [comment]
Closing in favor of #535

**Pull request closed without merging**
