### PR TITLE
Dockerize DB

### PR DESCRIPTION
**Pull request by azabujuban**
* In addition to testing with existing database instances this PR allows using dockerized instances
* Bumped versions of knex and pg used for tests
* Committed package-lock.json
* Removed a couple of console.logs that were polluting test output
* Removed the outdated node versions from the CI
* Updated to Babel 7

### CODE REVIEW

**Comment by lorensr** [comment]
Thanks for the contribution! Definitely an improvement 😊 When I do `npm run db-up` and `npm run test`, I get this error:

```
> join-monster@2.1.1 db-up /Users/me/gh/join-monster
> docker-compose -f ./docker/docker-compose.yml up -d

docker_postgres_1 is up-to-date
docker_adminer_1 is up-to-date
docker_mysql_1 is up-to-date
join-monster git:(upstream ⚡ docker) $ nt

> join-monster@2.1.1 test /Users/me/gh/join-monster
> bin/test --no-oracle

 running with all joins 
 testing sqlite3

> join-monster@2.1.1 testsqlite3 /Users/me/gh/join-monster
> NODE_ENV=test ava test/*.js

(node:94298) UnhandledPromiseRejectionWarning: /Users/me/gh/join-monster/node_modules/ava/lib/serialize-error.js:39
                } catch {}
                        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/me/gh/join-monster/node_modules/ava/lib/api.js:18:24)
(node:94298) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:94298) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 testing MySQL

...
```

**Comment by azabujuban** [comment]
Sorry for the delay in reply :(

Which version of node are you using? ava [doesn't](https://github.com/avajs/ava/blob/master/docs/support-statement.md) support [unsupported](https://github.com/nodejs/Release#release-schedule) node versions so anything less than 10 might not work.

I tested with node v6 and it wasn't working, but node v10 worked

**Comment by lorensr** [comment]
Thanks @azabujuban. So the tests shouldn't work on v8, but the package should still work on v8, right? 

Testing works for me on v12, but not v10. Any idea?

```

> join-monster@2.1.2 test /Users/me/gh/join-monster
> bin/test --no-oracle

 running with all joins 
 testing sqlite3

> join-monster@2.1.2 testsqlite3 /Users/me/gh/join-monster
> NODE_ENV=test ava test/*.js


  ✖ Couldn’t find any files to test

  ✖ Internal error
  TypeError: Cannot read property 'on' of null
  TypeError: Cannot read property 'on' of null
      at module.exports (/Users/me/gh/join-monster/node_modules/ava/lib/fork.js:40:20)
      at pMap (/Users/me/gh/join-monster/node_modules/ava/lib/api.js:232:20)
      at /Users/me/gh/join-monster/node_modules/p-map/index.js:57:28
      at process._tickCallback (internal/process/next_tick.js:68:7)

...
```

**Comment by azabujuban** [comment]
Looks like it's due to versions mismatch for different packages and node? I tried deleting `package-lock.json` and reinstalling everything (or doing `npm rebuild`) after changing the version of node and tests seem to run

**Pull request merged**
