### PR TITLE
Support binding parameters

### PR DESCRIPTION
**Pull request by s97712**
support binding parameters, add a few api for this [https://github.com/s97712/sqlbind.js](https://github.com/s97712/sqlbind.js)

### CODE REVIEW

**Comment by belgac** [comment]
Hello, does this support oracle as an engine yet? I think it's not the case when i had a quick glance at your library, am i wrong?

**Comment by belgac** [comment]
> Hello, does this support oracle as an engine yet? I think it's not the case when i had a quick glance at your library, am i wrong?

Ok the sql dialect should work with oracle

**Comment by lorensr** [comment]
Sorry for the radio silence! We're forming a new team to maintain this repo and respond to PRs, if you're interested: #399

**Comment by alexbbt** [comment]
This is outdated and had many unnecessary changes. A new PR should be opened to make this change in the future.

**Pull request closed without merging**
